//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.21 at 09:42:42 AM UTC 
//


package tech.inceptive.ai4czc.entsoedataretrieval.fetcher.xjc;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ESMP_DateTimeInterval complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ESMP_DateTimeInterval"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="start" type="{urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0}YMDHM_DateTime"/&gt;
 *         &lt;element name="end" type="{urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0}YMDHM_DateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ESMP_DateTimeInterval", propOrder = {
    "start",
    "end"
})
public class ESMPDateTimeInterval {

    @XmlElement(required = true)
    protected String start;
    @XmlElement(required = true)
    protected String end;

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStart(String value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnd(String value) {
        this.end = value;
    }
    
    /**
     * 
     * @return Start date but as {@link LocalDateTime} (the date is in ISO 8601 format)
     */
    public LocalDateTime getLDTStart() {
        return LocalDateTime.parse(start, DateTimeFormatter.ISO_DATE_TIME);
    }
    
    /**
     * 
     * @return End date but as {@link LocalDateTime} (the date is in ISO 8601 format)
     */
    public LocalDateTime getLDTEnd() {
        return LocalDateTime.parse(end, DateTimeFormatter.ISO_DATE_TIME);
    }

}
