//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.21 at 09:42:42 AM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tech.inceptive.ai4czc.entsoedataretrieval.fetcher.xjc;
