//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.19 at 01:50:32 PM UTC 
//


package tech.inceptive.ai4czc.entsoedataretrieval.fetcher.xjc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Publication_MarketDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Publication_MarketDocument"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mRID" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}ID_String"/&gt;
 *         &lt;element name="revisionNumber" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}ESMPVersion_String"/&gt;
 *         &lt;element name="type" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}MessageKind_String"/&gt;
 *         &lt;element name="sender_MarketParticipant.mRID" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}PartyID_String"/&gt;
 *         &lt;element name="sender_MarketParticipant.marketRole.type" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}MarketRoleKind_String"/&gt;
 *         &lt;element name="receiver_MarketParticipant.mRID" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}PartyID_String" minOccurs="0"/&gt;
 *         &lt;element name="receiver_MarketParticipant.marketRole.type" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}MarketRoleKind_String" minOccurs="0"/&gt;
 *         &lt;element name="createdDateTime" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}ESMP_DateTime"/&gt;
 *         &lt;element name="period.timeInterval" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}ESMP_DateTimeInterval"/&gt;
 *         &lt;element name="domain.mRID" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}AreaID_String" minOccurs="0"/&gt;
 *         &lt;element name="TimeSeries" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}TimeSeries" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * Please note that the used name space here is the GLMarketDocument one. When deserializing with this, always fix the 
 * namespace with a NamespaceFilter
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Publication_MarketDocument", propOrder = {
    "mrid",
    "revisionNumber",
    "type",
    "senderMarketParticipantMRID",
    "senderMarketParticipantMarketRoleType",
    "receiverMarketParticipantMRID",
    "receiverMarketParticipantMarketRoleType",
    "createdDateTime",
    "periodTimeInterval",
    "domainMRID",
    "timeSeries"
})
@XmlRootElement(name = "Publication_MarketDocument")
public class PublicationMarketDocument {

    @XmlElement(name = "mRID", required = true)
    protected String mrid;
    @XmlElement(required = true)
    protected String revisionNumber;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(name = "sender_MarketParticipant.mRID", required = true)
    protected PartyIDString senderMarketParticipantMRID;
    @XmlElement(name = "sender_MarketParticipant.marketRole.type", required = true)
    protected String senderMarketParticipantMarketRoleType;
    @XmlElement(name = "receiver_MarketParticipant.mRID")
    protected PartyIDString receiverMarketParticipantMRID;
    @XmlElement(name = "receiver_MarketParticipant.marketRole.type")
    protected String receiverMarketParticipantMarketRoleType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDateTime;
    @XmlElement(name = "period.timeInterval", required = true)
    protected ESMPDateTimeInterval periodTimeInterval;
    @XmlElement(name = "domain.mRID")
    protected AreaIDString domainMRID;
    @XmlElement(name = "TimeSeries", required = true)
    protected List<TimeSeries> timeSeries;

    /**
     * Gets the value of the mrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMRID() {
        return mrid;
    }

    /**
     * Sets the value of the mrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMRID(String value) {
        this.mrid = value;
    }

    /**
     * Gets the value of the revisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionNumber() {
        return revisionNumber;
    }

    /**
     * Sets the value of the revisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionNumber(String value) {
        this.revisionNumber = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the senderMarketParticipantMRID property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIDString }
     *     
     */
    public PartyIDString getSenderMarketParticipantMRID() {
        return senderMarketParticipantMRID;
    }

    /**
     * Sets the value of the senderMarketParticipantMRID property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIDString }
     *     
     */
    public void setSenderMarketParticipantMRID(PartyIDString value) {
        this.senderMarketParticipantMRID = value;
    }

    /**
     * Gets the value of the senderMarketParticipantMarketRoleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderMarketParticipantMarketRoleType() {
        return senderMarketParticipantMarketRoleType;
    }

    /**
     * Sets the value of the senderMarketParticipantMarketRoleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderMarketParticipantMarketRoleType(String value) {
        this.senderMarketParticipantMarketRoleType = value;
    }

    /**
     * Gets the value of the receiverMarketParticipantMRID property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIDString }
     *     
     */
    public PartyIDString getReceiverMarketParticipantMRID() {
        return receiverMarketParticipantMRID;
    }

    /**
     * Sets the value of the receiverMarketParticipantMRID property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIDString }
     *     
     */
    public void setReceiverMarketParticipantMRID(PartyIDString value) {
        this.receiverMarketParticipantMRID = value;
    }

    /**
     * Gets the value of the receiverMarketParticipantMarketRoleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverMarketParticipantMarketRoleType() {
        return receiverMarketParticipantMarketRoleType;
    }

    /**
     * Sets the value of the receiverMarketParticipantMarketRoleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverMarketParticipantMarketRoleType(String value) {
        this.receiverMarketParticipantMarketRoleType = value;
    }

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDateTime(XMLGregorianCalendar value) {
        this.createdDateTime = value;
    }

    /**
     * Gets the value of the periodTimeInterval property.
     * 
     * @return
     *     possible object is
     *     {@link ESMPDateTimeInterval }
     *     
     */
    public ESMPDateTimeInterval getPeriodTimeInterval() {
        return periodTimeInterval;
    }

    /**
     * Sets the value of the periodTimeInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESMPDateTimeInterval }
     *     
     */
    public void setPeriodTimeInterval(ESMPDateTimeInterval value) {
        this.periodTimeInterval = value;
    }

    /**
     * Gets the value of the domainMRID property.
     * 
     * @return
     *     possible object is
     *     {@link AreaIDString }
     *     
     */
    public AreaIDString getDomainMRID() {
        return domainMRID;
    }

    /**
     * Sets the value of the domainMRID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaIDString }
     *     
     */
    public void setDomainMRID(AreaIDString value) {
        this.domainMRID = value;
    }

    /**
     * Gets the value of the timeSeries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeSeries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeSeries }
     * 
     * 
     */
    public List<TimeSeries> getTimeSeries() {
        if (timeSeries == null) {
            timeSeries = new ArrayList<TimeSeries>();
        }
        return this.timeSeries;
    }

}
