//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.21 at 09:42:42 AM UTC 
//


package tech.inceptive.ai4czc.entsoedataretrieval.fetcher.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StandardQualityTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StandardQualityTypeList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="A01"/&gt;
 *     &lt;enumeration value="A02"/&gt;
 *     &lt;enumeration value="A03"/&gt;
 *     &lt;enumeration value="A04"/&gt;
 *     &lt;enumeration value="A05"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StandardQualityTypeList", namespace = "urn:entsoe.eu:wgedi:codelists")
@XmlEnum
public enum StandardQualityTypeList {


    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;Adjusted&lt;/Title&gt;
     *               &lt;Definition&gt;The contents of the object have been adjusted.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A01")
    A_01("A01"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;Not available&lt;/Title&gt;
     *               &lt;Definition&gt;The contents of the object are not available.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A02")
    A_02("A02"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;Estimated&lt;/Title&gt;
     *               &lt;Definition&gt;The contents of the object are estimated.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A03")
    A_03("A03"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;As provided&lt;/Title&gt;
     *               &lt;Definition&gt;The contents of the object are as provided.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A04")
    A_04("A04"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;Incomplete&lt;/Title&gt;
     *               &lt;Definition&gt;The contents of the object are calculated based on incomplete data.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A05")
    A_05("A05");
    private final String value;

    StandardQualityTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StandardQualityTypeList fromValue(String v) {
        for (StandardQualityTypeList c: StandardQualityTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
