//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.21 at 09:42:42 AM UTC 
//


package tech.inceptive.ai4czc.entsoedataretrieval.fetcher.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StandardIndicatorTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StandardIndicatorTypeList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="A01"/&gt;
 *     &lt;enumeration value="A02"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StandardIndicatorTypeList", namespace = "urn:entsoe.eu:wgedi:codelists")
@XmlEnum
public enum StandardIndicatorTypeList {


    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;YES&lt;/Title&gt;
     *               &lt;Definition&gt;A positive indication.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A01")
    A_01("A01"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;NO&lt;/Title&gt;
     *               &lt;Definition&gt;A negative indication.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A02")
    A_02("A02");
    private final String value;

    StandardIndicatorTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StandardIndicatorTypeList fromValue(String v) {
        for (StandardIndicatorTypeList c: StandardIndicatorTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
