//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.21 at 09:42:42 AM UTC 
//


package tech.inceptive.ai4czc.entsoedataretrieval.fetcher.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StandardAllocationModeTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StandardAllocationModeTypeList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="A01"/&gt;
 *     &lt;enumeration value="A02"/&gt;
 *     &lt;enumeration value="A03"/&gt;
 *     &lt;enumeration value="A04"/&gt;
 *     &lt;enumeration value="A05"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StandardAllocationModeTypeList", namespace = "urn:entsoe.eu:wgedi:codelists")
@XmlEnum
public enum StandardAllocationModeTypeList {


    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;Order by price with pro rata&lt;/Title&gt;
     *               &lt;Definition&gt;The allocation method is by price with eventual pro rata.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A01")
    A_01("A01"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;Order by price with first come - first served&lt;/Title&gt;
     *               &lt;Definition&gt;The allocation method is by price with eventual use of first come first served.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A02")
    A_02("A02"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;First come - First served&lt;/Title&gt;
     *               &lt;Definition&gt;The allocation method is first come first served.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A03")
    A_03("A03"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;Pro rata&lt;/Title&gt;
     *               &lt;Definition&gt;The allocation method is pro rata.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A04")
    A_04("A04"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     *               &lt;Title&gt;Continuous&lt;/Title&gt;
     *               &lt;Definition&gt;The allocation method is continuous, i.e. there is no gate closure time when bids from the market participants are collected. Instead allocation procedure takes place immediately.&lt;/Definition&gt;
     *             &lt;/CodeDescription&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("A05")
    A_05("A05");
    private final String value;

    StandardAllocationModeTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StandardAllocationModeTypeList fromValue(String v) {
        for (StandardAllocationModeTypeList c: StandardAllocationModeTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
