//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.19 at 01:50:32 PM UTC 
//
package tech.inceptive.ai4czc.entsoedataretrieval.fetcher.xjc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for TimeSeries complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TimeSeries"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mRID" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}ID_String"/&gt;
 *         &lt;element name="auction.mRID" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}ID_String" minOccurs="0"/&gt;
 *         &lt;element name="auction.type" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}AuctionKind_String" minOccurs="0"/&gt;
 *         &lt;element name="auction.category" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}Category_String" minOccurs="0"/&gt;
 *         &lt;element name="businessType" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}BusinessKind_String"/&gt;
 *         &lt;element name="in_Domain.mRID" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}AreaID_String"/&gt;
 *         &lt;element name="out_Domain.mRID" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}AreaID_String"/&gt;
 *         &lt;element name="contract_MarketAgreement.type" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}CapacityContractKind_String" minOccurs="0"/&gt;
 *         &lt;element name="quantity_Measure_Unit.name" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}MeasurementUnitKind_String" minOccurs="0"/&gt;
 *         &lt;element name="currency_Unit.name" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}CurrencyCode_String" minOccurs="0"/&gt;
 *         &lt;element name="price_Measure_Unit.name" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}MeasurementUnitKind_String" minOccurs="0"/&gt;
 *         &lt;element name="classificationSequence_AttributeInstanceComponent.position" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="participantNumber_AttributeInstanceComponent.position" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="winnerParticipantNumber_AttributeInstanceComponent.position" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="curveType" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}CurveType_String" minOccurs="0"/&gt;
 *         &lt;element name="Period" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}Series_Period" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Reason" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}Reason" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Winners_MarketParticipant" type="{urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0}Winners_MarketParticipant" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeSeries", propOrder = {
    "mrid",
    "auctionMRID",
    "auctionType",
    "auctionCategory",
    "businessType",
    "biddingZoneDomainMRID",
    "objectAggregation",
    "inBiddingZoneDomainMRID",
    "outBiddingZoneDomainMRID",
    "registeredResourceMRID",
    "registeredResourceName",
    "quantityMeasureUnitName",
    "inDomainMRID",
    "outDomainMRID",
    "startDateAndOrTimeDate",
    "startDateAndOrTimeTime",
    "endDateAndOrTimeDate",
    "endDateAndOrTimeTime",
    "contractMarketAgreementType",
    "currencyUnitName",
    "priceMeasureUnitName",
    "classificationSequenceAttributeInstanceComponentPosition",
    "participantNumberAttributeInstanceComponentPosition",
    "winnerParticipantNumberAttributeInstanceComponentPosition",
    "curveType",
    "productionRegisteredResourceMRID",
    "productionRegisteredResourceName",
    "productionRegisteredResourceLocationName",
    "productionRegisteredResourcePSRTypePsrType",
    "productionRegisteredResourcePSRTypePowerSystemResourcesMRID",
    "productionRegisteredResourcePSRTypePowerSystemResourcesName",
    "productionRegisteredResourcePSRTypePowerSystemResourcesNominalP",
    "assetRegisteredResource",
    "availablePeriod",
    "windPowerFeedinPeriod",
    "cancelledTS",
    "mktPSRType",
    "period",
    "reason",
    "winnersMarketParticipant"
})
public class TimeSeries {

    @XmlElement(name = "mRID", required = true)
    protected String mrid;
    @XmlElement(name = "auction.mRID")
    protected String auctionMRID;
    @XmlElement(name = "auction.type")
    protected String auctionType;
    @XmlElement(name = "auction.category")
    protected String auctionCategory;
    @XmlElement(required = true)
    protected String businessType;
    @XmlElement(name = "biddingZone_Domain.mRID")
    protected AreaIDString biddingZoneDomainMRID;
    @XmlElement(required = true)
    protected String objectAggregation;
    @XmlElement(name = "inBiddingZone_Domain.mRID")
    protected AreaIDString inBiddingZoneDomainMRID;
    @XmlElement(name = "outBiddingZone_Domain.mRID")
    protected AreaIDString outBiddingZoneDomainMRID;
    @XmlElement(name = "registeredResource.mRID")
    protected ResourceIDString registeredResourceMRID;
    @XmlElement(name = "registeredResource.name")
    protected String registeredResourceName;
    @XmlElement(name = "quantity_Measure_Unit.name")
    protected String quantityMeasureUnitName;
    @XmlElement(name = "in_Domain.mRID")
    protected AreaIDString inDomainMRID;
    @XmlElement(name = "out_Domain.mRID")
    protected AreaIDString outDomainMRID;
    @XmlElement(name = "start_DateAndOrTime.date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDateAndOrTimeDate;
    @XmlElement(name = "start_DateAndOrTime.time")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar startDateAndOrTimeTime;
    @XmlElement(name = "end_DateAndOrTime.date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDateAndOrTimeDate;
    @XmlElement(name = "end_DateAndOrTime.time")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar endDateAndOrTimeTime;
    @XmlElement(name = "contract_MarketAgreement.type")
    protected String contractMarketAgreementType;
    @XmlElement(name = "currency_Unit.name")
    protected String currencyUnitName;
    @XmlElement(name = "price_Measure_Unit.name")
    protected String priceMeasureUnitName;
    @XmlElement(name = "classificationSequence_AttributeInstanceComponent.position")
    protected BigInteger classificationSequenceAttributeInstanceComponentPosition;
    @XmlElement(name = "participantNumber_AttributeInstanceComponent.position")
    protected BigInteger participantNumberAttributeInstanceComponentPosition;
    @XmlElement(name = "winnerParticipantNumber_AttributeInstanceComponent.position")
    protected BigInteger winnerParticipantNumberAttributeInstanceComponentPosition;
    protected String curveType;
    @XmlElement(name = "production_RegisteredResource.mRID")
    protected ResourceIDString productionRegisteredResourceMRID;
    @XmlElement(name = "production_RegisteredResource.name")
    protected String productionRegisteredResourceName;
    @XmlElement(name = "production_RegisteredResource.location.name")
    protected String productionRegisteredResourceLocationName;
    @XmlElement(name = "production_RegisteredResource.pSRType.psrType")
    protected String productionRegisteredResourcePSRTypePsrType;
    @XmlElement(name = "production_RegisteredResource.pSRType.powerSystemResources.mRID")
    protected ResourceIDString productionRegisteredResourcePSRTypePowerSystemResourcesMRID;
    @XmlElement(name = "production_RegisteredResource.pSRType.powerSystemResources.name")
    protected String productionRegisteredResourcePSRTypePowerSystemResourcesName;
    @XmlElement(name = "production_RegisteredResource.pSRType.powerSystemResources.nominalP")
    protected ESMPActivePower productionRegisteredResourcePSRTypePowerSystemResourcesNominalP;
    @XmlElement(name = "Asset_RegisteredResource")
    protected List<AssetRegisteredResource> assetRegisteredResource;
    @XmlElement(name = "Available_Period")
    protected List<SeriesPeriod> availablePeriod;
    @XmlElement(name = "WindPowerFeedin_Period")
    protected List<SeriesPeriod> windPowerFeedinPeriod;
    protected String cancelledTS;
    @XmlElement(name = "MktPSRType")
    protected MktPSRType mktPSRType;
    @XmlElement(name = "Period")
    protected List<SeriesPeriod> period;
    @XmlElement(name = "Reason")
    protected List<Reason> reason;
    @XmlElement(name = "Winners_MarketParticipant")
    protected List<WinnersMarketParticipant> winnersMarketParticipant;

    /**
     * Gets the value of the mrid property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMRID() {
        return mrid;
    }

    /**
     * Sets the value of the mrid property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMRID(String value) {
        this.mrid = value;
    }

    /**
     * Gets the value of the auctionMRID property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAuctionMRID() {
        return auctionMRID;
    }

    /**
     * Sets the value of the auctionMRID property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAuctionMRID(String value) {
        this.auctionMRID = value;
    }

    /**
     * Gets the value of the auctionType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAuctionType() {
        return auctionType;
    }

    /**
     * Sets the value of the auctionType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAuctionType(String value) {
        this.auctionType = value;
    }

    /**
     * Gets the value of the auctionCategory property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAuctionCategory() {
        return auctionCategory;
    }

    /**
     * Sets the value of the auctionCategory property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAuctionCategory(String value) {
        this.auctionCategory = value;
    }

    /**
     * Gets the value of the businessType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * Sets the value of the businessType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBusinessType(String value) {
        this.businessType = value;
    }

    /**
     * Gets the value of the biddingZoneDomainMRID property.
     *
     * @return possible object is {@link AreaIDString }
     *
     */
    public AreaIDString getBiddingZoneDomainMRID() {
        return biddingZoneDomainMRID;
    }

    /**
     * Sets the value of the biddingZoneDomainMRID property.
     *
     * @param value allowed object is {@link AreaIDString }
     *
     */
    public void setBiddingZoneDomainMRID(AreaIDString value) {
        this.biddingZoneDomainMRID = value;
    }

    /**
     * Gets the value of the inDomainMRID property.
     *
     * @return possible object is {@link AreaIDString }
     *
     */
    public AreaIDString getInDomainMRID() {
        return inDomainMRID;
    }

    /**
     * Sets the value of the inDomainMRID property.
     *
     * @param value allowed object is {@link AreaIDString }
     *
     */
    public void setInDomainMRID(AreaIDString value) {
        this.inDomainMRID = value;
    }

    /**
     * Gets the value of the outDomainMRID property.
     *
     * @return possible object is {@link AreaIDString }
     *
     */
    public AreaIDString getOutDomainMRID() {
        return outDomainMRID;
    }

    /**
     * Sets the value of the outDomainMRID property.
     *
     * @param value allowed object is {@link AreaIDString }
     *
     */
    public void setOutDomainMRID(AreaIDString value) {
        this.outDomainMRID = value;
    }

    /**
     * Gets the value of the startDateAndOrTimeDate property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getStartDateAndOrTimeDate() {
        return startDateAndOrTimeDate;
    }

    /**
     * Sets the value of the startDateAndOrTimeDate property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setStartDateAndOrTimeDate(XMLGregorianCalendar value) {
        this.startDateAndOrTimeDate = value;
    }

    /**
     * Gets the value of the startDateAndOrTimeTime property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getStartDateAndOrTimeTime() {
        return startDateAndOrTimeTime;
    }

    /**
     * Sets the value of the startDateAndOrTimeTime property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setStartDateAndOrTimeTime(XMLGregorianCalendar value) {
        this.startDateAndOrTimeTime = value;
    }

    /**
     * Gets the value of the endDateAndOrTimeDate property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getEndDateAndOrTimeDate() {
        return endDateAndOrTimeDate;
    }

    /**
     * Sets the value of the endDateAndOrTimeDate property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setEndDateAndOrTimeDate(XMLGregorianCalendar value) {
        this.endDateAndOrTimeDate = value;
    }

    /**
     * Gets the value of the endDateAndOrTimeTime property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getEndDateAndOrTimeTime() {
        return endDateAndOrTimeTime;
    }

    /**
     * Sets the value of the endDateAndOrTimeTime property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setEndDateAndOrTimeTime(XMLGregorianCalendar value) {
        this.endDateAndOrTimeTime = value;
    }

    /**
     * Gets the value of the contractMarketAgreementType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getContractMarketAgreementType() {
        return contractMarketAgreementType;
    }

    /**
     * Sets the value of the contractMarketAgreementType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setContractMarketAgreementType(String value) {
        this.contractMarketAgreementType = value;
    }

    /**
     * Gets the value of the quantityMeasureUnitName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getQuantityMeasureUnitName() {
        return quantityMeasureUnitName;
    }

    /**
     * Sets the value of the quantityMeasureUnitName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setQuantityMeasureUnitName(String value) {
        this.quantityMeasureUnitName = value;
    }

    /**
     * Gets the value of the currencyUnitName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCurrencyUnitName() {
        return currencyUnitName;
    }

    /**
     * Sets the value of the currencyUnitName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCurrencyUnitName(String value) {
        this.currencyUnitName = value;
    }

    /**
     * Gets the value of the priceMeasureUnitName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPriceMeasureUnitName() {
        return priceMeasureUnitName;
    }

    /**
     * Sets the value of the priceMeasureUnitName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPriceMeasureUnitName(String value) {
        this.priceMeasureUnitName = value;
    }

    /**
     * Gets the value of the classificationSequenceAttributeInstanceComponentPosition property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getClassificationSequenceAttributeInstanceComponentPosition() {
        return classificationSequenceAttributeInstanceComponentPosition;
    }

    /**
     * Sets the value of the classificationSequenceAttributeInstanceComponentPosition property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setClassificationSequenceAttributeInstanceComponentPosition(BigInteger value) {
        this.classificationSequenceAttributeInstanceComponentPosition = value;
    }

    /**
     * Gets the value of the participantNumberAttributeInstanceComponentPosition property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getParticipantNumberAttributeInstanceComponentPosition() {
        return participantNumberAttributeInstanceComponentPosition;
    }

    /**
     * Sets the value of the participantNumberAttributeInstanceComponentPosition property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setParticipantNumberAttributeInstanceComponentPosition(BigInteger value) {
        this.participantNumberAttributeInstanceComponentPosition = value;
    }

    /**
     * Gets the value of the winnerParticipantNumberAttributeInstanceComponentPosition property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getWinnerParticipantNumberAttributeInstanceComponentPosition() {
        return winnerParticipantNumberAttributeInstanceComponentPosition;
    }

    /**
     * Sets the value of the winnerParticipantNumberAttributeInstanceComponentPosition property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setWinnerParticipantNumberAttributeInstanceComponentPosition(BigInteger value) {
        this.winnerParticipantNumberAttributeInstanceComponentPosition = value;
    }

    /**
     * Gets the value of the curveType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCurveType() {
        return curveType;
    }

    /**
     * Sets the value of the curveType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCurveType(String value) {
        this.curveType = value;
    }
    
    /**
     * Gets the value of the productionRegisteredResourceMRID property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceIDString }
     *     
     */
    public ResourceIDString getProductionRegisteredResourceMRID() {
        return productionRegisteredResourceMRID;
    }

    /**
     * Sets the value of the productionRegisteredResourceMRID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceIDString }
     *     
     */
    public void setProductionRegisteredResourceMRID(ResourceIDString value) {
        this.productionRegisteredResourceMRID = value;
    }

    /**
     * Gets the value of the productionRegisteredResourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductionRegisteredResourceName() {
        return productionRegisteredResourceName;
    }

    /**
     * Sets the value of the productionRegisteredResourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductionRegisteredResourceName(String value) {
        this.productionRegisteredResourceName = value;
    }

    /**
     * Gets the value of the productionRegisteredResourceLocationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductionRegisteredResourceLocationName() {
        return productionRegisteredResourceLocationName;
    }

    /**
     * Sets the value of the productionRegisteredResourceLocationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductionRegisteredResourceLocationName(String value) {
        this.productionRegisteredResourceLocationName = value;
    }

    /**
     * Gets the value of the productionRegisteredResourcePSRTypePsrType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductionRegisteredResourcePSRTypePsrType() {
        return productionRegisteredResourcePSRTypePsrType;
    }

    /**
     * Sets the value of the productionRegisteredResourcePSRTypePsrType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductionRegisteredResourcePSRTypePsrType(String value) {
        this.productionRegisteredResourcePSRTypePsrType = value;
    }

    /**
     * Gets the value of the productionRegisteredResourcePSRTypePowerSystemResourcesMRID property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceIDString }
     *     
     */
    public ResourceIDString getProductionRegisteredResourcePSRTypePowerSystemResourcesMRID() {
        return productionRegisteredResourcePSRTypePowerSystemResourcesMRID;
    }

    /**
     * Sets the value of the productionRegisteredResourcePSRTypePowerSystemResourcesMRID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceIDString }
     *     
     */
    public void setProductionRegisteredResourcePSRTypePowerSystemResourcesMRID(ResourceIDString value) {
        this.productionRegisteredResourcePSRTypePowerSystemResourcesMRID = value;
    }

    /**
     * Gets the value of the productionRegisteredResourcePSRTypePowerSystemResourcesName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductionRegisteredResourcePSRTypePowerSystemResourcesName() {
        return productionRegisteredResourcePSRTypePowerSystemResourcesName;
    }

    /**
     * Sets the value of the productionRegisteredResourcePSRTypePowerSystemResourcesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductionRegisteredResourcePSRTypePowerSystemResourcesName(String value) {
        this.productionRegisteredResourcePSRTypePowerSystemResourcesName = value;
    }

    /**
     * Gets the value of the productionRegisteredResourcePSRTypePowerSystemResourcesNominalP property.
     * 
     * @return
     *     possible object is
     *     {@link ESMPActivePower }
     *     
     */
    public ESMPActivePower getProductionRegisteredResourcePSRTypePowerSystemResourcesNominalP() {
        return productionRegisteredResourcePSRTypePowerSystemResourcesNominalP;
    }

    /**
     * Sets the value of the productionRegisteredResourcePSRTypePowerSystemResourcesNominalP property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESMPActivePower }
     *     
     */
    public void setProductionRegisteredResourcePSRTypePowerSystemResourcesNominalP(ESMPActivePower value) {
        this.productionRegisteredResourcePSRTypePowerSystemResourcesNominalP = value;
    }

    /**
     * Gets the value of the assetRegisteredResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assetRegisteredResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssetRegisteredResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssetRegisteredResource }
     * 
     * 
     */
    public List<AssetRegisteredResource> getAssetRegisteredResource() {
        if (assetRegisteredResource == null) {
            assetRegisteredResource = new ArrayList<AssetRegisteredResource>();
        }
        return this.assetRegisteredResource;
    }

    /**
     * Gets the value of the availablePeriod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availablePeriod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailablePeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SeriesPeriod }
     * 
     * 
     */
    public List<SeriesPeriod> getAvailablePeriod() {
        if (availablePeriod == null) {
            availablePeriod = new ArrayList<SeriesPeriod>();
        }
        return this.availablePeriod;
    }

    /**
     * Gets the value of the windPowerFeedinPeriod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the windPowerFeedinPeriod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWindPowerFeedinPeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SeriesPeriod }
     * 
     * 
     */
    public List<SeriesPeriod> getWindPowerFeedinPeriod() {
        if (windPowerFeedinPeriod == null) {
            windPowerFeedinPeriod = new ArrayList<SeriesPeriod>();
        }
        return this.windPowerFeedinPeriod;
    }

    /**
     * Gets the value of the period property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the period property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriod().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link SeriesPeriod }
     *
     *
     */
    public List<SeriesPeriod> getPeriod() {
        if (period == null) {
            period = new ArrayList<SeriesPeriod>();
        }
        return this.period;
    }

    /**
     * Gets the value of the reason property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the reason property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReason().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Reason }
     *
     *
     */
    public List<Reason> getReason() {
        if (reason == null) {
            reason = new ArrayList<Reason>();
        }
        return this.reason;
    }

    /**
     * Gets the value of the winnersMarketParticipant property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the winnersMarketParticipant property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWinnersMarketParticipant().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link WinnersMarketParticipant }
     *
     *
     */
    public List<WinnersMarketParticipant> getWinnersMarketParticipant() {
        if (winnersMarketParticipant == null) {
            winnersMarketParticipant = new ArrayList<WinnersMarketParticipant>();
        }
        return this.winnersMarketParticipant;
    }

    public String getMrid() {
        return mrid;
    }

    public String getObjectAggregation() {
        return objectAggregation;
    }

    public AreaIDString getInBiddingZoneDomainMRID() {
        return inBiddingZoneDomainMRID;
    }

    public AreaIDString getOutBiddingZoneDomainMRID() {
        return outBiddingZoneDomainMRID;
    }

    public ResourceIDString getRegisteredResourceMRID() {
        return registeredResourceMRID;
    }

    public String getRegisteredResourceName() {
        return registeredResourceName;
    }

    public String getCancelledTS() {
        return cancelledTS;
    }

    public MktPSRType getMktPSRType() {
        return mktPSRType;
    }

    public void setMrid(String mrid) {
        this.mrid = mrid;
    }

    public void setObjectAggregation(String objectAggregation) {
        this.objectAggregation = objectAggregation;
    }

    public void setInBiddingZoneDomainMRID(AreaIDString inBiddingZoneDomainMRID) {
        this.inBiddingZoneDomainMRID = inBiddingZoneDomainMRID;
    }

    public void setOutBiddingZoneDomainMRID(AreaIDString outBiddingZoneDomainMRID) {
        this.outBiddingZoneDomainMRID = outBiddingZoneDomainMRID;
    }

    public void setRegisteredResourceMRID(ResourceIDString registeredResourceMRID) {
        this.registeredResourceMRID = registeredResourceMRID;
    }

    public void setRegisteredResourceName(String registeredResourceName) {
        this.registeredResourceName = registeredResourceName;
    }

    public void setCancelledTS(String cancelledTS) {
        this.cancelledTS = cancelledTS;
    }

    public void setMktPSRType(MktPSRType mktPSRType) {
        this.mktPSRType = mktPSRType;
    }

}
