//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.09 at 02:13:47 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iec62325.351:tc57wg16:451-5:statusrequestdocument:4:0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tech.inceptive.ai4czc.entsoedataretrieval.fetcher.xjc.statusrequest;
