//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.09 at 02:13:47 PM UTC 
//


package tech.inceptive.ai4czc.entsoedataretrieval.fetcher.xjc.statusrequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StandardCodingSchemeTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StandardCodingSchemeTypeList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="A01"/&gt;
 *     &lt;enumeration value="A02"/&gt;
 *     &lt;enumeration value="A10"/&gt;
 *     &lt;enumeration value="NAD"/&gt;
 *     &lt;enumeration value="NAL"/&gt;
 *     &lt;enumeration value="NAM"/&gt;
 *     &lt;enumeration value="NAT"/&gt;
 *     &lt;enumeration value="NAZ"/&gt;
 *     &lt;enumeration value="NBA"/&gt;
 *     &lt;enumeration value="NBE"/&gt;
 *     &lt;enumeration value="NBG"/&gt;
 *     &lt;enumeration value="NCH"/&gt;
 *     &lt;enumeration value="NCS"/&gt;
 *     &lt;enumeration value="NCZ"/&gt;
 *     &lt;enumeration value="NDE"/&gt;
 *     &lt;enumeration value="NDK"/&gt;
 *     &lt;enumeration value="NEE"/&gt;
 *     &lt;enumeration value="NES"/&gt;
 *     &lt;enumeration value="NFI"/&gt;
 *     &lt;enumeration value="NFR"/&gt;
 *     &lt;enumeration value="NGB"/&gt;
 *     &lt;enumeration value="NGE"/&gt;
 *     &lt;enumeration value="NGI"/&gt;
 *     &lt;enumeration value="NGR"/&gt;
 *     &lt;enumeration value="NHR"/&gt;
 *     &lt;enumeration value="NHU"/&gt;
 *     &lt;enumeration value="NIE"/&gt;
 *     &lt;enumeration value="NIT"/&gt;
 *     &lt;enumeration value="NKG"/&gt;
 *     &lt;enumeration value="NKZ"/&gt;
 *     &lt;enumeration value="NLI"/&gt;
 *     &lt;enumeration value="NLT"/&gt;
 *     &lt;enumeration value="NLU"/&gt;
 *     &lt;enumeration value="NLV"/&gt;
 *     &lt;enumeration value="NMA"/&gt;
 *     &lt;enumeration value="NMD"/&gt;
 *     &lt;enumeration value="NMK"/&gt;
 *     &lt;enumeration value="NNL"/&gt;
 *     &lt;enumeration value="NNN"/&gt;
 *     &lt;enumeration value="NNO"/&gt;
 *     &lt;enumeration value="NPL"/&gt;
 *     &lt;enumeration value="NPT"/&gt;
 *     &lt;enumeration value="NRO"/&gt;
 *     &lt;enumeration value="NRU"/&gt;
 *     &lt;enumeration value="NSE"/&gt;
 *     &lt;enumeration value="NSI"/&gt;
 *     &lt;enumeration value="NSK"/&gt;
 *     &lt;enumeration value="NTR"/&gt;
 *     &lt;enumeration value="NUA"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StandardCodingSchemeTypeList", namespace = "urn:entsoe.eu:wgedi:codelists")
@XmlEnum
public enum StandardCodingSchemeTypeList {


    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;EIC&lt;/Title&gt;&lt;Definition&gt;The coding scheme is the Energy Identification Coding Scheme (EIC), maintained by ENTSO-E.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A01")
    A_01("A01"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;CGM&lt;/Title&gt;&lt;Definition&gt;The coding scheme used for Common Grid Model Exchange Standard (CGMES).&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A02")
    A_02("A02"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;GS1&lt;/Title&gt;&lt;Definition&gt;The coding scheme for the preceding attribute is the Global Location Number (GLN 13) or Global Service Relation Number (GSRN 18), maintained by GS1.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A10")
    A_10("A10"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Andorra National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NAD("NAD"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Albania National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NAL("NAL"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Armenia National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NAM("NAM"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Austria National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NAT("NAT"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Azerbaijan National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NAZ("NAZ"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Bosnia and Herzegovina National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NBA("NBA"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Belgium National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NBE("NBE"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Bulgaria National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NBG("NBG"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Switzerland National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NCH("NCH"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Serbia and Montenegro National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NCS("NCS"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Czech Republic National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NCZ("NCZ"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Germany National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NDE("NDE"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Denmark National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NDK("NDK"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Estonia National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NEE("NEE"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Spain National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NES("NES"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Finland National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NFI("NFI"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;France National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NFR("NFR"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;United Kingdom National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NGB("NGB"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Georgia National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NGE("NGE"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Gibraltar National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NGI("NGI"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Greece National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NGR("NGR"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Croatia National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NHR("NHR"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Hungary National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NHU("NHU"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Ireland National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NIE("NIE"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Italy National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NIT("NIT"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Kyrgyzstan National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NKG("NKG"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Kazakhstan National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NKZ("NKZ"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Liechtenstein National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NLI("NLI"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Lithuania National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NLT("NLT"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Luxembourg National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NLU("NLU"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Latvia National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NLV("NLV"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Morocco National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NMA("NMA"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Moldavia National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NMD("NMD"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Macedonia National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NMK("NMK"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Netherlands National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NNL("NNL"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Nordic Regional coding scheme&lt;/Title&gt;&lt;Definition&gt;The coding scheme of the Nordic region which covers Denmark, Finland, Norway and Sweden.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NNN("NNN"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Norway National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NNO("NNO"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Poland National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NPL("NPL"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Portugal National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NPT("NPT"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Romania National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NRO("NRO"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Russian Federation National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NRU("NRU"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Sweden National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NSE("NSE"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Slovenia National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NSI("NSI"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Slovakia National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NSK("NSK"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Turkey National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NTR("NTR"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Ukraine National coding scheme&lt;/Title&gt;&lt;Definition&gt;The National coding scheme of the country in question.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    NUA("NUA");
    private final String value;

    StandardCodingSchemeTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StandardCodingSchemeTypeList fromValue(String v) {
        for (StandardCodingSchemeTypeList c: StandardCodingSchemeTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
