//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.09 at 02:13:47 PM UTC 
//


package tech.inceptive.ai4czc.entsoedataretrieval.fetcher.xjc.statusrequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StandardStatusTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StandardStatusTypeList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="A01"/&gt;
 *     &lt;enumeration value="A02"/&gt;
 *     &lt;enumeration value="A03"/&gt;
 *     &lt;enumeration value="A04"/&gt;
 *     &lt;enumeration value="A05"/&gt;
 *     &lt;enumeration value="A06"/&gt;
 *     &lt;enumeration value="A07"/&gt;
 *     &lt;enumeration value="A08"/&gt;
 *     &lt;enumeration value="A09"/&gt;
 *     &lt;enumeration value="A10"/&gt;
 *     &lt;enumeration value="A11"/&gt;
 *     &lt;enumeration value="A12"/&gt;
 *     &lt;enumeration value="A13"/&gt;
 *     &lt;enumeration value="A14"/&gt;
 *     &lt;enumeration value="A15"/&gt;
 *     &lt;enumeration value="A16"/&gt;
 *     &lt;enumeration value="A17"/&gt;
 *     &lt;enumeration value="A18"/&gt;
 *     &lt;enumeration value="A19"/&gt;
 *     &lt;enumeration value="A20"/&gt;
 *     &lt;enumeration value="A21"/&gt;
 *     &lt;enumeration value="A22"/&gt;
 *     &lt;enumeration value="A23"/&gt;
 *     &lt;enumeration value="A24"/&gt;
 *     &lt;enumeration value="A25"/&gt;
 *     &lt;enumeration value="A26"/&gt;
 *     &lt;enumeration value="A27"/&gt;
 *     &lt;enumeration value="A28"/&gt;
 *     &lt;enumeration value="A29"/&gt;
 *     &lt;enumeration value="A30"/&gt;
 *     &lt;enumeration value="A31"/&gt;
 *     &lt;enumeration value="A32"/&gt;
 *     &lt;enumeration value="A33"/&gt;
 *     &lt;enumeration value="A34"/&gt;
 *     &lt;enumeration value="A35"/&gt;
 *     &lt;enumeration value="A36"/&gt;
 *     &lt;enumeration value="A37"/&gt;
 *     &lt;enumeration value="A38"/&gt;
 *     &lt;enumeration value="A39"/&gt;
 *     &lt;enumeration value="A40"/&gt;
 *     &lt;enumeration value="A41"/&gt;
 *     &lt;enumeration value="A42"/&gt;
 *     &lt;enumeration value="A43"/&gt;
 *     &lt;enumeration value="A44"/&gt;
 *     &lt;enumeration value="A45"/&gt;
 *     &lt;enumeration value="A46"/&gt;
 *     &lt;enumeration value="A47"/&gt;
 *     &lt;enumeration value="A48"/&gt;
 *     &lt;enumeration value="A49"/&gt;
 *     &lt;enumeration value="A50"/&gt;
 *     &lt;enumeration value="A51"/&gt;
 *     &lt;enumeration value="A52"/&gt;
 *     &lt;enumeration value="A53"/&gt;
 *     &lt;enumeration value="A54"/&gt;
 *     &lt;enumeration value="A55"/&gt;
 *     &lt;enumeration value="A56"/&gt;
 *     &lt;enumeration value="A57"/&gt;
 *     &lt;enumeration value="A58"/&gt;
 *     &lt;enumeration value="A59"/&gt;
 *     &lt;enumeration value="A60"/&gt;
 *     &lt;enumeration value="A61"/&gt;
 *     &lt;enumeration value="A62"/&gt;
 *     &lt;enumeration value="A63"/&gt;
 *     &lt;enumeration value="A64"/&gt;
 *     &lt;enumeration value="A65"/&gt;
 *     &lt;enumeration value="A66"/&gt;
 *     &lt;enumeration value="A67"/&gt;
 *     &lt;enumeration value="A68"/&gt;
 *     &lt;enumeration value="A69"/&gt;
 *     &lt;enumeration value="A70"/&gt;
 *     &lt;enumeration value="A71"/&gt;
 *     &lt;enumeration value="A72"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StandardStatusTypeList", namespace = "urn:entsoe.eu:wgedi:codelists")
@XmlEnum
public enum StandardStatusTypeList {


    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Intermediate&lt;/Title&gt;&lt;Definition&gt;The document is in a non finalized state.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A01")
    A_01("A01"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Final&lt;/Title&gt;&lt;Definition&gt;The document is in a definitive state.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A02")
    A_02("A02"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Deactivated&lt;/Title&gt;&lt;Definition&gt;The object being reported has been deactivated.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A03")
    A_03("A03"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Reactivated&lt;/Title&gt;&lt;Definition&gt;The object being reported has been reactivated.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A04")
    A_04("A04"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Active&lt;/Title&gt;&lt;Definition&gt;The object being reported is currently active.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A05")
    A_05("A05"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Available&lt;/Title&gt;&lt;Definition&gt;The volumes (one or more) are available.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A06")
    A_06("A06"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Activated&lt;/Title&gt;&lt;Definition&gt;The quantities in the time series have been activated.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A07")
    A_07("A07"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;In process&lt;/Title&gt;&lt;Definition&gt;The quantities in the time series are in the process of activation (an activation request has been made).&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A08")
    A_08("A08"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Cancelled&lt;/Title&gt;&lt;Definition&gt;The tender indicated in the time series has been completely cancelled.
     * In this case the resources are no longer available to all Acquiring System Operators&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A09")
    A_09("A09"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Ordered&lt;/Title&gt;&lt;Definition&gt;The quantities in the time series are to be activated.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A10")
    A_10("A10"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Unavailable&lt;/Title&gt;&lt;Definition&gt;The volumes (one or more) are unavailable.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A11")
    A_11("A11"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;RGCE agreed&lt;/Title&gt;&lt;Definition&gt;The information has been agreed within the ENTSO-E Regional Group Continental Europe process.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A12")
    A_12("A12"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Withdrawn&lt;/Title&gt;&lt;Definition&gt;The information has been withdrawn by the submitter.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A13")
    A_13("A13"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Creation&lt;/Title&gt;&lt;Definition&gt;The action requested to be carried out is the creation of a new object.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A14")
    A_14("A14"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Update&lt;/Title&gt;&lt;Definition&gt;The action requested to be carried out is the update an existing object.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A15")
    A_15("A15"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Deactivation&lt;/Title&gt;&lt;Definition&gt;The action requested to be carried out is to deactivate an existing object.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A16")
    A_16("A16"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Reactivation&lt;/Title&gt;&lt;Definition&gt;The action requested to be carried out is to reactivate a previously deactivated object.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A17")
    A_17("A17"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Preventive&lt;/Title&gt;&lt;Definition&gt;The remedial action is applied to prevent an outage.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A18")
    A_18("A18"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Curative&lt;/Title&gt;&lt;Definition&gt;The remedial action is applied after an outage has occurred, in order to maintain the operational security.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A19")
    A_19("A19"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Automatic&lt;/Title&gt;&lt;Definition&gt;The remedial action being described is applied by an automation when an outage occurs.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A20")
    A_20("A20"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Open&lt;/Title&gt;&lt;Definition&gt;The action being described consists of disconnecting the network element  to the transmission network.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A21")
    A_21("A21"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Close&lt;/Title&gt;&lt;Definition&gt;The action being described consists of connecting the network element  to the transmission network.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A22")
    A_22("A22"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Stop&lt;/Title&gt;&lt;Definition&gt;The action being described consists of stopping the production or consumption connected to a network element.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A23")
    A_23("A23"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Start&lt;/Title&gt;&lt;Definition&gt;The action being described consists of starting the production or consumption connected to a network element.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A24")
    A_24("A24"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Relative&lt;/Title&gt;&lt;Definition&gt;The quantity being described is a relative value to an initial state.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A25")
    A_25("A25"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Absolute&lt;/Title&gt;&lt;Definition&gt;The quantity being described is an absolute value.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A26")
    A_26("A26"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Curative or preventive&lt;/Title&gt;&lt;Definition&gt;The remedial action can be applied to prevent an outage or after an outage has occurred in order to maintain the operational security.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A27")
    A_27("A27"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Unshared bid&lt;/Title&gt;&lt;Definition&gt;Used to indicate that the bid cannot be shared.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A28")
    A_28("A28"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Pre Processed&lt;/Title&gt;&lt;Definition&gt;to be process&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A29")
    A_29("A29"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Substituted&lt;/Title&gt;&lt;Definition&gt;Substituted pre-processing data.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A30")
    A_30("A30"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Modified&lt;/Title&gt;&lt;Definition&gt;Modified pre-processing data by RSC or CGMA platform.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A31")
    A_31("A31"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Result&lt;/Title&gt;&lt;Definition&gt;Result&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A32")
    A_32("A32"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Not satisfied&lt;/Title&gt;&lt;Definition&gt;The need described in the time series cannot be satisfied.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A33")
    A_33("A33"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Rejected&lt;/Title&gt;&lt;Definition&gt;The document rejected by one or more parties.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A34")
    A_34("A34"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Preliminary&lt;/Title&gt;&lt;Definition&gt;Indicative information only for initial planning purposes.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A35")
    A_35("A35"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Planned&lt;/Title&gt;&lt;Definition&gt;Is planned.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A36")
    A_36("A36"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Confirmed&lt;/Title&gt;&lt;Definition&gt;The status is  confirmed.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A37")
    A_37("A37"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Shall Be Used&lt;/Title&gt;&lt;Definition&gt;The object defined in the series shall be used.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A38")
    A_38("A38"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Could Be Used&lt;/Title&gt;&lt;Definition&gt;The object defined in the series could be used.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A39")
    A_39("A39"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Proposed&lt;/Title&gt;&lt;Definition&gt;The status of the information is proposed.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A40")
    A_40("A40"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Individual Network Data&lt;/Title&gt;&lt;Definition&gt;The network data provided in the document or series concerns the the unique TSO area describes by the document or series.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A41")
    A_41("A41"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Common Network Data&lt;/Title&gt;&lt;Definition&gt;The network data provided in the document or series concerns the whole area describes by the document or series.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A42")
    A_42("A42"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Setpoint schedule&lt;/Title&gt;&lt;Definition&gt;The code for the power setpoint mode of operation of the HVDC link.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A43")
    A_43("A43"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Proportional external signal&lt;/Title&gt;&lt;Definition&gt;The code for the proportional external signal mode of operation of the HVDC link.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A44")
    A_44("A44"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;AC emulation&lt;/Title&gt;&lt;Definition&gt;The code for the AC emulation mode of operation of the HVDC link.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A45")
    A_45("A45"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Importing element&lt;/Title&gt;&lt;Definition&gt;An importing network element in which the flow measurement enters.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A46")
    A_46("A46"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Exporting element&lt;/Title&gt;&lt;Definition&gt;An exporting network element from which the flow measurement comes out.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A47")
    A_47("A47"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;To be optimized&lt;/Title&gt;&lt;Definition&gt;Describes an element which needs to be optimized by an optimization process.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A48")
    A_48("A48"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;To be monitored&lt;/Title&gt;&lt;Definition&gt;Describes an element which needs to be monitored by an optimization process.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A49")
    A_49("A49"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;To be included in capacity calculation&lt;/Title&gt;&lt;Definition&gt;Describes an element which needs to be taken into account in a capacity calculation process.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A50")
    A_50("A50"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Relative to previous point in time&lt;/Title&gt;&lt;Definition&gt;The quantity being described is a relative value to a previous point in time.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A51")
    A_51("A51"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;For flow optimization&lt;/Title&gt;&lt;Definition&gt;Describes an element which needs to be optimized by a flow optimization process.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A52")
    A_52("A52"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;For voltage optimization&lt;/Title&gt;&lt;Definition&gt;Describes an element which needs to be optimized by a voltage optimization process.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A53")
    A_53("A53"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Presolved&lt;/Title&gt;&lt;Definition&gt;Describes an active constraint that limits the exchanges. It is part of the presolved domain.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A54")
    A_54("A54"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Not available if linked bid activated&lt;/Title&gt;&lt;Definition&gt;Bid not available if linked bid activated.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A55")
    A_55("A55"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Not available if linked bid rejected&lt;/Title&gt;&lt;Definition&gt;Bid not available if linked bid rejected.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A56")
    A_56("A56"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Not available for DA if linked bid subject to DA&lt;/Title&gt;&lt;Definition&gt;Bid not available for direct activation if linked bid subject to direct activation.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A57")
    A_57("A57"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Not available for DA if linked bid subject to SA&lt;/Title&gt;&lt;Definition&gt;Bid not available for direct activation if linked bid subject to scheduled activation.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A58")
    A_58("A58"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Not available if linked bid subject to SA&lt;/Title&gt;&lt;Definition&gt;Bid not available if linked bid subject to scheduled activation.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A59")
    A_59("A59"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Not available if linked bid subject to DA&lt;/Title&gt;&lt;Definition&gt;Bid not available if linked bid subject to direct activation.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A60")
    A_60("A60"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Primary market&lt;/Title&gt;&lt;Definition&gt;A value is traded for the first time.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A61")
    A_61("A61"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Secondary market&lt;/Title&gt;&lt;Definition&gt;A value is traded for the second or next times between two parties.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A62")
    A_62("A62"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Interesting&lt;/Title&gt;&lt;Definition&gt;Describes an asset which is considered as interesting.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A63")
    A_63("A63"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Relevant&lt;/Title&gt;&lt;Definition&gt;Describes an asset which is considered as relevant.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A64")
    A_64("A64"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Conditionally available&lt;/Title&gt;&lt;Definition&gt;Bid available as long as none of the conditions associated with the linked bids materialise.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A65")
    A_65("A65"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Conditionally unavailable&lt;/Title&gt;&lt;Definition&gt;Bid unavailable as long as none of the conditions associated with the linked bids materialise.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A66")
    A_66("A66"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Available if linked bid activated&lt;/Title&gt;&lt;Definition&gt;Bid available if linked bid activated.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A67")
    A_67("A67"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Available if linked bid rejected&lt;/Title&gt;&lt;Definition&gt;Bid available if linked bid rejected.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A68")
    A_68("A68"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Available if linked bid subject to SA&lt;/Title&gt;&lt;Definition&gt;Bid available if linked bid subject to scheduled activation.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A69")
    A_69("A69"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Available if linked bid subject to DA&lt;/Title&gt;&lt;Definition&gt;Bid available if linked bid subject to direct activation.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A70")
    A_70("A70"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Available for DA if linked bid subject to DA&lt;/Title&gt;&lt;Definition&gt;Bid available for direct activation if linked bid subject to direct activation.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A71")
    A_71("A71"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeDescription xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;Title&gt;Available for DA if linked bid subject to SA&lt;/Title&gt;&lt;Definition&gt;Bid available for direct activation if linked bid subject to scheduled activation.&lt;/Definition&gt;&lt;/CodeDescription&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("A72")
    A_72("A72");
    private final String value;

    StandardStatusTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StandardStatusTypeList fromValue(String v) {
        for (StandardStatusTypeList c: StandardStatusTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
